
version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: root
    ports: [ "5432:5432" ]

  redis:
    image: redis:7
    ports: [ "6379:6379" ]

  kafka:
    image: bitnami/kafka:3
    environment:
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
    ports: [ "9092:9092" ]

  zookeeper:
    image: bitnami/zookeeper:3
    ports: [ "2181:2181" ]
