spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/movie
    username: postgres
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  data:
    redis:
      host: localhost
      port: 6379
      password:
      timeout: 2000

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: booking-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      enable-auto-commit: true

  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: classpath:public.pem

cinema:
  security:
    jwt:
      user-id-claim: sub

server:
  port: 8085