spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/movie
    username: postgres
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: classpath:public.pem

cinema:
  security:
    jwt:
      user-id-claim: sub

minio:
  url: http://localhost:9000
  access-key: 5PfJfdPpv9492wCFGXf6
  secret-key: Sl1STEhdPdgR5sviIuPKYq3PeftoTOlNTSEf2U2q
  bucket: cinema-media
  public-url: http://localhost:9000

logging:
  level:
    org.springframework.security: DEBUG

server:
  port: 8082